spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/simple_online_shop
    name: postgres
    password: postgres
    hikari:
      minimum-idle: 2
      maximum-pool-size: 5
      data-source-properties: reWriteBatchedInserts=true